# Sonatype Lift configuration
# https://help.sonatype.com/lift/configuring-lift
# https://help.sonatype.com/lift/configuring-lift/build-and-.toml-details

jdkVersion = "11"
build = "gradlew build assemble"
