# To get started with Dependabot version updates, you'll need to specify, which
# package ecosystems to update and where the package manifests are located.
# Documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
    reviewers:
      - "amal"
    labels:
      - "gradle"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci(GitHub)"
    schedule:
      interval: "weekly"
    reviewers:
      - "amal"
    labels:
      - "gh-action"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
    reviewers:
      - "amal"
    labels:
      - "js"
      - "dependencies"
