name: Benchmark

on:
  schedule:
    - cron: '0 10 * * 2'
  push:
    paths:
      - '**/**Benchmark.kt'
      - '**/benchmark-summary.main.kts'
      - '**/benchmark.yml'

jobs:
  os-checks:
    strategy:
      fail-fast: false
      matrix:
        java: [ '11' ]
        os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]

    name: 'Benchmark on ${{ matrix.os }} JDK ${{ matrix.java }}'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden Runner
        if: matrix.os == 'ubuntu-latest'
        uses: step-security/harden-runner@8f144f8401c4e3693085dff03603f617f566ec6b
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.java }}'

      - name: 'Benchmark on ${{ matrix.os }}'
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
          jmh: 'IncrementIntent.*'
          jmh_wi: 3
          jmh_i: 6
          jmh_f: 3
        with:
          gradle-home-cache-cleanup: true
          arguments: jmh --stacktrace --no-configuration-cache --scan

      - name: Summary
        run: ./.github/workflows/benchmark-summary.main.kts >> $GITHUB_STEP_SUMMARY
        shell: bash
